@extends('layouts.index')

@section('content')
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ea architecto voluptatum repudiandae minima? Rerum, natus doloremque expedita impedit minus ad. Expedita in, illo numquam possimus facere perspiciatis deserunt quisquam cumque.</p>
    <p>Soluta earum porro, sit nam maiores labore? Magnam minus tenetur provident earum! Blanditiis quas error et nihil veritatis ex natus, consequatur quo, necessitatibus magnam optio amet dolorum illum molestias! Harum?</p>
    <p>Itaque nobis aperiam autem facilis dolorum ullam ratione vero est consequatur blanditiis? Officiis sunt sint error repudiandae quidem, repellendus minima quas cum in debitis laboriosam delectus quod sit fuga esse.</p>
    <p>Excepturi accusamus dolorem aut nemo cupiditate ullam quibusdam delectus voluptate voluptatibus aliquid dolorum natus facere esse explicabo maxime nam, quas sapiente labore repudiandae dolores neque? Aliquid consequatur officiis eum quibusdam?</p>
    <p>Debitis, non rerum aut voluptatem officia eum? Quis dolores sunt nulla! Inventore, veniam! Nisi asperiores, aspernatur doloremque consequatur rem, impedit veritatis maiores saepe error atque est suscipit, officiis nulla. Atque!</p>
    <p>Repellendus similique voluptatum voluptatem sunt dolores a aut qui eius aliquam maxime corporis, nihil impedit perferendis nisi ipsum cum fugit, quidem hic optio facilis amet sapiente? Modi quibusdam possimus distinctio.</p>
    <p>Quisquam quod vel repudiandae similique unde ad molestias mollitia et veritatis maxime error incidunt, maiores natus! Perspiciatis tenetur atque obcaecati aspernatur odio laudantium, dolor esse, at non tempore, quae quia.</p>
    <p>Quaerat voluptas, consectetur vero distinctio, natus ducimus, nihil deleniti quos voluptatibus nemo labore! Nihil alias at, assumenda sed esse in illo eos soluta corporis adipisci non fugiat numquam mollitia doloremque.</p>
    <p>Maxime minus ad iure sed, recusandae accusamus maiores reprehenderit, laborum quibusdam aperiam tempora illo praesentium! Eligendi in iusto illo rem ea. Suscipit ex soluta iure hic! Asperiores a ad velit!</p>
    <p>Perspiciatis ratione officiis et odit explicabo culpa expedita alias dignissimos ut. Ea id, eligendi officia consequatur reiciendis ipsam, sequi exercitationem tempora non, consectetur libero quos hic numquam alias distinctio repellat?</p>
    <p>Asperiores atque tenetur temporibus quas ipsam veniam cumque ex nostrum, saepe laudantium animi neque minus beatae, illo doloribus perferendis excepturi. Quam aspernatur labore, dolorem eveniet commodi nulla neque beatae laboriosam!</p>
    <p>Praesentium consequatur, eligendi temporibus, optio rerum possimus saepe tempore sunt nemo, nobis quasi tempora laudantium perferendis ducimus enim expedita vero dicta vel quas ab necessitatibus! Veniam sed inventore perspiciatis dolorum?</p>
    <p>Inventore ullam iure laudantium assumenda deleniti eaque, amet dolorem? Inventore distinctio blanditiis consectetur maxime possimus quis voluptates fugiat adipisci id, tempore minus dolorem eos perspiciatis commodi natus, voluptatibus eligendi corporis.</p>
    <p>Animi ratione culpa dolor sapiente eveniet! Veniam, a quis! Dolor iste illum cupiditate libero architecto id quos, nostrum dolores, aut maxime at nam amet totam dignissimos magnam! Vel, magnam explicabo?</p>
    <p>Eius asperiores alias quo suscipit quidem consectetur animi explicabo dolor, autem nihil quae libero cum, error voluptate deleniti similique illum harum dolores nisi reiciendis! Officiis et repellat quibusdam ipsum exercitationem!</p>
    <p>Dolorem praesentium perferendis inventore, nisi voluptate accusantium. Obcaecati nobis reiciendis quaerat in explicabo quam optio similique assumenda reprehenderit. Rerum voluptate dolor commodi ad, accusamus officiis facere tempora at libero voluptas.</p>
    <p>Numquam rem libero iusto cumque omnis repellendus beatae eaque ducimus, nostrum ipsum quaerat nesciunt, quae dolorum. Aspernatur itaque ea, maiores mollitia accusantium id quos, quidem dolorum eaque aut non iusto.</p>
    <p>Quisquam at ipsum similique nesciunt consequatur. Perferendis consequatur officia, quia, veniam aliquam fuga itaque ullam eum similique enim blanditiis a eveniet quisquam veritatis qui, voluptatem debitis sed exercitationem reprehenderit facere!</p>
    <p>Asperiores quasi sequi officia, perferendis assumenda delectus voluptate ullam illum fugiat magni excepturi placeat sed saepe minus qui, veniam dolores distinctio eveniet aut eligendi enim cupiditate? Recusandae earum sint distinctio?</p>
    <p>Labore, beatae quos neque velit veritatis enim. Perspiciatis officia in quaerat cumque blanditiis consequuntur maiores dolor nulla cupiditate voluptas tenetur recusandae ut, ad quibusdam vero quas beatae corporis nam odit.</p>
@endsection
